pipeline:
  database-config:
    neo4j-uri: ${NEO4J_URI}
    neo4j-username: ${NEO4J_USERNAME}
    neo4j-password: ${NEO4J_PASSWORD}
    neo4j-database: ${NEO4J_DATABASE}
  stages:
    - type: ingestion
      tools:
        - package: tools.person_loader
          name: PersonLoader
          url: ${PERSON_URL}
        - package: tools.education_loader
          name: EducationLoader
          url: ${EDUCATION_URL}
        - package: tools.experience_loader
          name: ExperienceLoader
          url: ${EXPERIENCE_URL}
        - package: tools.language_loader
          name: LanguageLoader
          url: ${LANGUAGE_URL}
        - package: tools.honour_awards_loader
          name: HonourAwardsLoader
          url: ${HONOUR_AWARDS_URL}
        - package: tools.recommendation_loader
          name: RecommendationLoader
          url: ${RECOMMENDATION_URL}
        - package: tools.blog_loader
          name: BlogLoader
          url: ${BLOG_URL}
        - package: tools.projects_loader
          name: ProjectsLoader
          url: ${PROJECTS_URL}
        - package: tools.certifications_loader
          name: CertificationsLoader
          url: ${CERTIFICATIONS_URL}
    - type: comprehension
      tools:
        - package: comprehension.node_comprehender
          name: NodeComprehender

llm-model:
  id: chat_groq
  name: chat-groq-model
  provider: chat_groq
  config:
    base-url: ${CHAT_GROQ_API_BASE}
    model: chat-groq-model
    api-key: ${CHAT_GROQ_API_KEY}
    rpm: 1680
    tpm: 280000

embeddings-model:
  id: huggingface
  name: huggingface-embedding
  provider: huggingface
  config:
    model: sentence-transformers/all-MiniLM-L6-v2
    cache-dir: ${HF_CACHE_DIR}
    use-auth-token: ${HF_AUTH_TOKEN}

